all: hello_c hello_c_syscall hello_c_syscall_2

hello_c: hello.c
	gcc -o hello_c hello.c

hello_c_syscall: hello_syscall.c
	gcc -o hello_c_syscall hello_syscall.c

hello_c_syscall_2: hello_syscall_2.c
	gcc -o hello_c_syscall_2 hello_syscall_2.c

clean:
	rm hello_c hello_c_syscall hello_c_syscall_2
	
